"use client";

import Link from "next/link";
import { ArrowRight, Bot, Building2, FlaskConical } from "lucide-react";
import { DATASET_KEYS, DATASET_META, datasets, type DatasetKey } from "@/lib/data";
import { ThemeToggle } from "./theme-toggle";

const ICONS: Record<DatasetKey, typeof FlaskConical> = {
  demo: FlaskConical,
  mvp: Building2,
};

export function LaunchChooser() {
  return (
    <div className="mx-auto flex min-h-screen w-full max-w-4xl flex-col gap-8 px-4 py-10 sm:px-6">
      <header className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          <div className="flex size-9 items-center justify-center rounded-xl bg-accent/10 text-accent">
            <Bot className="size-5" />
          </div>
          <div>
            <h1 className="text-base font-bold leading-tight">Accrual Agent</h1>
            <p className="text-xs text-muted">Autonomous month-end close</p>
          </div>
        </div>
        <ThemeToggle />
      </header>

      <div className="flex flex-col gap-2">
        <h2 className="text-xl font-bold">Choose a dataset to run the close against</h2>
        <p className="text-sm text-muted">
          Both run the identical agent and the same 2026-06 close — they differ
          only in the books underneath. Pick one to begin; you can switch anytime.
        </p>
      </div>

      <div className="grid gap-4 sm:grid-cols-2">
        {DATASET_KEYS.map((key) => {
          const meta = DATASET_META[key];
          const Icon = ICONS[key];
          const period = datasets[key].period;
          const lineCount = datasets[key].steps.at(-1)?.lines.length ?? 0;
          return (
            <Link
              key={key}
              href={{ pathname: "/", query: { mode: key, day: "day-1" } }}
              className="group flex flex-col gap-4 rounded-2xl border border-border bg-card p-6 shadow-sm transition-colors hover:border-accent"
            >
              <div className="flex items-center justify-between">
                <div className="flex size-11 items-center justify-center rounded-xl bg-accent/10 text-accent">
                  <Icon className="size-6" />
                </div>
                <span className="rounded-full border border-border px-2 py-0.5 text-[10px] font-semibold uppercase tracking-wide text-muted">
                  {meta.tagline}
                </span>
              </div>
              <div>
                <h3 className="text-lg font-bold leading-tight">{meta.label}</h3>
                <p className="text-sm font-medium text-accent">{meta.company}</p>
              </div>
              <p className="flex-1 text-sm text-muted">{meta.blurb}</p>
              <div className="flex items-center justify-between text-xs text-muted">
                <span>
                  {lineCount} accrual lines · {period}
                </span>
                <span className="inline-flex items-center gap-1 font-semibold text-foreground">
                  Launch
                  <ArrowRight className="size-3.5 transition-transform group-hover:translate-x-0.5" />
                </span>
              </div>
            </Link>
          );
        })}
      </div>

      <footer className="mt-auto pt-6 text-center text-[11px] text-muted">
        Demo environment — all vendors, amounts, and emails are simulated. The
        SeatGeek dataset is generated by{" "}
        <code>scripts/generate_seatgeek_dataset.py</code> and kept deliberately
        separate from the sample walkthrough.
      </footer>
    </div>
  );
}
